### ISSUE TITLE
item.Name not leading to results? Not very tech savvy.

### ISSUE THREAD

**Issue by butthatswrongyoufuckingspiral** [ccbrown/poe-go#1]
As subject states, I've tried running the indexer with a small modification, changing the if item.Type == "Ancient Reliquary Key" { line to if item.Name == "Tabula Rasa Simple Robe" for example but it leads to zero results even when poe.trade is constantly getting new Tabula's.

Just trying to figure this thing out for now as I'm terrible with computers.

**Comment by ccbrown** [comment]
The names have some markup and look something like this: `<<set:MS>><<set:M>><<set:S>>Roth's Reach`. It's kinda weird, but that's how the API provides them: https://www.pathofexile.com/developer/docs/api-resource-public-stash-tabs

You could probably add "strings" to the imports at the top of your file and do something like `if strings.Contains(item.Name, "Tabula Rasa")`

I'll see if I can figure out how to make this more intuitive. If nothing else, it probably warrants documentation. You're the second one to ask about this.

**Comment by butthatswrongyoufuckingspiral** [comment]
Ha, glad I wasn't the only one feeling like a complete idiot. The only type of code I've ever touched is an obscure language used in a program called Dream Maker.

Thank you so much for the information!

PS: Seems to be working splendidly, thanks again, issue/question resolved!
