### ISSUE TITLE
other poe version,

### ISSUE THREAD

**Issue by Bucky0604** [ccbrown/poe-go#2]
I don't know how to use other poe version's api and change id, how you can teach me how to make it,Thank you

**Comment by ccbrown** [comment]
For context, this guy is wanting a solution to fight back against bots on Garena servers. He has also been messaging me privately and posting on Reddit: https://www.reddit.com/r/pathofexiledev/comments/5ziutk/i_have_a_garena_api_and_next_change_idlike/

This is a library and guide to programming. It is intended for use by those with an interest in programming. Countering bots or even providing fully packaged indexers is beyond the scope of this project. The library can be used with Garena servers (see `OpenPublicStashTabSubscriptionForHost`), and I will give all of the code-level support asked of me (I've given a lot for this in private messages already.). But it seems an end-user solution is the thing being requested here, and I'm simply not willing to commit to that.
