### ISSUE TITLE
Cannot find package ccbrown/poe-go/api in any of:

### ISSUE THREAD

**Issue by Haroldyolo** [ccbrown/poe-go#3]
Hi,

Trying to follow step by step the readme, but came onto this error when trying to install the dependencies.
Any idea?

**Comment by ccbrown** [comment]
Can you copy / paste the full output of the command?

**Comment by Haroldyolo** [comment]
here you go:

/c/go/src/poe-indexing-101
$ go get -v .
main.go:11:2: cannot find package "github.com/ccbrown/poe-go/api" in any of:
        C:\Go\src\vendor\github.com\ccbrown\poe-go\api (vendor tree)
        C:\Go\src\github.com\ccbrown\poe-go\api (from $GOROOT)
        C:\Users\Robysan\go\src\github.com\ccbrown\poe-go\api (from $GOPATH)

**Comment by ccbrown** [comment]
Try moving the directory from `/c/go/src/poe-indexing-101` to `/c/Users/Robysan/go/src/poe-indexing-101`. You can do this in the file explorer or via command line:

```
cd /c/
mkdir -p ~/go/src
mv /c/go/src/poe-indexing-101 ~/go/src/poe-indexing-101
```

Then change to that directory:

```
cd ~/go/src/poe-indexing-101
```

("~" is shorthand for "/c/Users/Robysan")

**Comment by Haroldyolo** [comment]
This one now comes up:
Robysan@ROBYSAN-PC ~/Go/src/poe-indexing-101
$ go get -v .
package github.com/ccbrown/poe-go/api: cannot download, C:\Users\Robysan\go is a GOROOT, not a GOPATH. For more details see: 'go help gopath'

It's good to mention that my Go is installed under c:\Go which was the default installation directory.

**Comment by Haroldyolo** [comment]
I ran this as well to check which one is my gopath root and this comes up:

Robysan@ROBYSAN-PC ~/Go/src/poe-indexing-101
$ go env GOPATH
C:\Users\Robysan\go

**Comment by ccbrown** [comment]
I think somehow or another, you got some files in your GOPATH (C:\Users\Robysan\go) that shouldn't be there. You installed Go to C:\Go, so C:\Users\Robysan\go should be completely empty except for the directory and file you put there. I would try deleting that directory entirely and running the command again:

```
cd ~
mv ~/go/src/poe-indexing-101 ~/poe-indexing-101-tmp
rm -rf ~/go
mkdir -p ~/go/src
mv ~/poe-indexing-101-tmp ~/go/src/poe-indexing-101
cd ~/go/src/poe-indexing-101
```

**Comment by Haroldyolo** [comment]
Robysan@ROBYSAN-PC ~/go/src/poe-indexing-101
$ go get -v .
github.com/ccbrown/poe-go (download)
go install: no install location for c:\Users\Robysan\go\src\poe-indexing-101: hidden by C:\Go\src\poe-indexing-101

It found the github now, but for some reason it doesn't want to install it. No idea what does hidde by mean. I checked and there isn't any other folder there even if I check show hidden files.

**Comment by ccbrown** [comment]
Well, it seems like we're closer... To make absolutely sure that "C:\Go\src\poe-indexing-101" directory doesn't exist, maybe try this?

```
rm -rf /c/go/src/poe-indexing-101
```

And maybe also this:

```
rm -rf /c/go/pkg/poe-indexing-101
```

**Comment by Haroldyolo** [comment]
That did the trick !!! Thanks a lot for your co-operation! I am over the moon with your fast response. I am pretty sure I will be contacting you soon again with programming/tweaking question about the indexer. 

Thanks a lot again! You are a star!

**Comment by ccbrown** [comment]
No problem! I want to make it clear though that the indexer is meant to be an introductory to programming with the PoE API rather than a ready-to-use-out-of-the-box solution. I'm happy to help, but if you ask too many questions, at some point I just have to say "I'm leaving that as an exercise for you to figure out.". ;)

Best of luck!
